const store = {
  users: [
    {
      id: 1,
      photo: 'https://c.files.bbci.co.uk/D6E6/production/_109241055_mediaitem109241054.jpg',
      name: 'Debby Smith',
      email: 'debbysmith@gmail.com',
      address: '655 Generic St',
      state: 'CA',
      zip: 24890,
      isAdmin: false,
    },
    {
      id: 2,
      photo: 'https://c.files.bbci.co.uk/D6E6/production/_109241055_mediaitem109241054.jpg',
      name: 'Karen Connely',
      email: 'speaktomgr@gmail.com',
      address: '489 Street St',
      state: 'WA',
      zip: 28780,
      isAdmin: false,
    },
    {
      id: 3,
      photo: 'https://c.files.bbci.co.uk/D6E6/production/_109241055_mediaitem109241054.jpg',
      name: 'Sharon Sumpter',
      email: 'sharon@gmail.com',
      address: '25789 Road St',
      state: 'PA',
      zip: 90145,
      isAdmin: false,
    },
    {
      id: 4,
      photo: 'https://c.files.bbci.co.uk/D6E6/production/_109241055_mediaitem109241054.jpg',
      name: 'Sarah Phelps',
      email: 'something@gmail.com',
      address: '90210 Monticello St',
      state: 'WA',
      zip: 25439,
      isAdmin: true,
    }
  ],

  items: [
    {
      id: 1,
      photo: 'https://www.rollingstone.com/wp-content/uploads/2020/05/Screen-Shot-2020-05-21-at-13.02.55.png',
      title: 'SAES Tee',
      price: 50,
      description: 'comfortable tee',
      date_created: '11-10-2020',
    },
    {
      id: 2,
      photo: 'https://static.nike.com/a/images/t_default/vh9zxzpuumh98ctxdxbw/gym-club-kids-duffel-bag-DNTBjb81.jpg',
      title: 'SAES Gym Bag',
      price: 60,
      description: 'spacious gym bag',
      date_created: '11-10-2020',
    },
    {
      id: 3,
      photo: 'https://www.rollingstone.com/wp-content/uploads/2020/05/Screen-Shot-2020-05-21-at-13.02.55.png',
      title: 'SAES Tee',
      price: 50,
      description: 'comfortable tee',
      date_created: '11-10-2020',
    },
    {
      id: 4,
      photo: 'https://www.rollingstone.com/wp-content/uploads/2020/05/Screen-Shot-2020-05-21-at-13.02.55.png',
      title: 'SAES Tee',
      price: 50,
      description: 'comfortable tee',
      date_created: '11-10-2020',
    },
    {
      id: 5,
      photo: 'https://www.rollingstone.com/wp-content/uploads/2020/05/Screen-Shot-2020-05-21-at-13.02.55.png',
      title: 'SAES Tee',
      price: 50,
      description: 'comfortable tee',
      date_created: '11-10-2020',
    },
  ],

  programs: [
    {
      id: 1,
      title: 'Booty Bootcamp',
      price: 60,
      description: 'Work da booty',
      date_created: '11-10-2020',
    },
    {
      id: 2,
      title: 'Ab Shredder',
      price: 70,
      description: 'Shred those abs',
      date_created: '11-10-2020',
    },
  ],

  user_reviews: [
    {
      id: 1,
      content: 'Comfortable shirt',
      rating: 5,
      date_created: '11/10/2020',
      programId: null,
      itemId: 1,
      userId: 1,
    },
    {
      id: 2,
      content: 'My abs are killing me!',
      rating: 5,
      date_created: '11/01/2020',
      programId: 2,
      itemId: null,
      userId: 3,
    },
  ],

  user_purchases: [
    {
      id: 1,
      title: 'Ab Shredder',
      price: 70,
      type: 'program',
      userId: 2,
      itemId: null,
      programId: 2,
    },
    {
      id: 2,
      title: 'SAES Tee',
      price: 50,
      type: 'apparel',
      userId: 1,
      itemId: 1,
      programId: null,
    },
  ],
};
export default store;
